--------------------------------------------------------
-- Archivo creado  - miércoles-octubre-05-2011   
--------------------------------------------------------
--  DDL for Table ACCCAT1
--------------------------------------------------------

  CREATE TABLE "PRESUPUESTO"."ACCCAT1" 
   (	"B_CODROL" VARCHAR2(5 BYTE), 
	"B_CODCAT1" VARCHAR2(20 BYTE), 
	"USRCRE" VARCHAR2(30 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(30 BYTE), 
	"FECACT" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
 

   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT1"."B_CODROL" IS 'Código de rol';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT1"."B_CODCAT1" IS 'Código de categoría1';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT1"."USRCRE" IS 'usuario de creación de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT1"."FECCRE" IS 'Fecha de creación de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT1"."USRACT" IS 'Usuario de actualización de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT1"."FECACT" IS 'Fecha de actualización de registro';
 
   COMMENT ON TABLE "PRESUPUESTO"."ACCCAT1"  IS 'ACCESO A CATEGORIA1 PARA REPORTES';
--------------------------------------------------------
--  DDL for Table ACCCAT2
--------------------------------------------------------

  CREATE TABLE "PRESUPUESTO"."ACCCAT2" 
   (	"B_CODROL" VARCHAR2(5 BYTE), 
	"B_CODCAT1" VARCHAR2(10 BYTE), 
	"B_CODCAT2" VARCHAR2(10 BYTE), 
	"USRCRE" VARCHAR2(30 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(20 BYTE), 
	"FECACT" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
 

   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT2"."B_CODROL" IS 'Código de rol';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT2"."B_CODCAT1" IS 'Código de categoría1';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT2"."B_CODCAT2" IS 'Código de categoría2';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT2"."USRCRE" IS 'Usuario de creación de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT2"."FECCRE" IS 'Fecha de creación de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT2"."USRACT" IS 'Usuario de actualización de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT2"."FECACT" IS 'Fecha de actualización de registro';
 
   COMMENT ON TABLE "PRESUPUESTO"."ACCCAT2"  IS 'ACCESO A CATEGORIA2 PARA REPORTE';
--------------------------------------------------------
--  DDL for Table ACCCAT3
--------------------------------------------------------

  CREATE TABLE "PRESUPUESTO"."ACCCAT3" 
   (	"B_CODROL" VARCHAR2(5 BYTE), 
	"B_CODCAT1" VARCHAR2(10 BYTE), 
	"B_CODCAT2" VARCHAR2(10 BYTE), 
	"B_CODCAT3" VARCHAR2(10 BYTE), 
	"USRCRE" VARCHAR2(30 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(20 BYTE), 
	"FECACT" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
 

   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT3"."B_CODROL" IS 'Código de rol';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT3"."B_CODCAT1" IS 'Código de categoría 1';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT3"."B_CODCAT2" IS 'Código de categoría 2';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT3"."B_CODCAT3" IS 'Código de categoría 3';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT3"."USRCRE" IS 'Usuario de creación de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT3"."FECCRE" IS 'Fecha de creación de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT3"."USRACT" IS 'Usuario de actualización de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT3"."FECACT" IS 'Fecha de actualización de registro';
 
   COMMENT ON TABLE "PRESUPUESTO"."ACCCAT3"  IS 'ACCESO A CATEGORIA 3 PARA REPORTES';
--------------------------------------------------------
--  DDL for Table ACCCAT4
--------------------------------------------------------

  CREATE TABLE "PRESUPUESTO"."ACCCAT4" 
   (	"B_CODROL" VARCHAR2(5 BYTE), 
	"B_CODCAT1" VARCHAR2(10 BYTE), 
	"B_CODCAT2" VARCHAR2(10 BYTE), 
	"B_CODCAT3" VARCHAR2(10 BYTE), 
	"B_CODCAT4" VARCHAR2(20 BYTE), 
	"USRCRE" VARCHAR2(10 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(10 BYTE), 
	"FECACT" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
 

   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT4"."B_CODROL" IS 'Código de rol';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT4"."B_CODCAT1" IS 'Código de categoría 1';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT4"."B_CODCAT2" IS 'Código de categoria 2';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT4"."B_CODCAT3" IS 'Código de categoría 3';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT4"."B_CODCAT4" IS 'Código de categoría 4';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT4"."USRCRE" IS 'Usuario de creación de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT4"."FECCRE" IS 'Fecha de creación de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT4"."USRACT" IS 'Usuario de actualización de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ACCCAT4"."FECACT" IS 'Fecha de actualización de registro';
 
   COMMENT ON TABLE "PRESUPUESTO"."ACCCAT4"  IS 'ACCESO A CATEGORIA 4 PARA REPORTES';
--------------------------------------------------------
--  DDL for Table ASOCAT
--------------------------------------------------------

  CREATE TABLE "PRESUPUESTO"."ASOCAT" 
   (	"B_CODCAT4" VARCHAR2(10 BYTE), 
	"CODPROC" VARCHAR2(20 BYTE), 
	"USRCRE" VARCHAR2(15 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(20 BYTE), 
	"FECACT" VARCHAR2(20 BYTE), 
	"UORG" VARCHAR2(10 BYTE), 
	"FECCAM" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
 

   COMMENT ON COLUMN "PRESUPUESTO"."ASOCAT"."B_CODCAT4" IS 'Categoría 4';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ASOCAT"."CODPROC" IS 'Código del proceso';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ASOCAT"."USRCRE" IS 'Usuario de creación de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ASOCAT"."FECCRE" IS 'fecha de creación';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ASOCAT"."USRACT" IS 'Usuario de actualización de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ASOCAT"."FECACT" IS 'Fecha de actualización de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ASOCAT"."UORG" IS 'Unidad de Origen';
 
   COMMENT ON COLUMN "PRESUPUESTO"."ASOCAT"."FECCAM" IS 'Fecha de cambio';
 
   COMMENT ON TABLE "PRESUPUESTO"."ASOCAT"  IS 'ASOCIACION DE CATEGORIA 4 A PROCESOS';
--------------------------------------------------------
--  DDL for Table BIAUDIT
--------------------------------------------------------

  CREATE TABLE "PRESUPUESTO"."BIAUDIT" 
   (	"FECACC" VARCHAR2(25 BYTE), 
	"DETFAZ" VARCHAR2(500 BYTE), 
	"RESULT" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
 

   COMMENT ON COLUMN "PRESUPUESTO"."BIAUDIT"."FECACC" IS 'Fecha hora del registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BIAUDIT"."DETFAZ" IS 'Detalle de la interfaz';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BIAUDIT"."RESULT" IS 'Resultado de la interfaz';
 
   COMMENT ON TABLE "PRESUPUESTO"."BIAUDIT"  IS 'AUDITORIA DE INTERFAZ';
--------------------------------------------------------
--  DDL for Table BVTCAT1
--------------------------------------------------------

  CREATE TABLE "PRESUPUESTO"."BVTCAT1" 
   (	"CODCAT1" VARCHAR2(10 BYTE), 
	"DESCAT1" VARCHAR2(50 BYTE), 
	"USRCRE" VARCHAR2(30 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(30 BYTE), 
	"FECACT" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
 

   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT1"."CODCAT1" IS 'Código de categoría 1';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT1"."DESCAT1" IS 'Descripción de categoría 1';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT1"."USRCRE" IS 'Usuario de creación de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT1"."FECCRE" IS 'Fecha de creación de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT1"."USRACT" IS 'Usuario de actualización de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT1"."FECACT" IS 'Fecha de actualización de registro';
 
   COMMENT ON TABLE "PRESUPUESTO"."BVTCAT1"  IS 'Categoría1';
--------------------------------------------------------
--  DDL for Table BVTCAT2
--------------------------------------------------------

  CREATE TABLE "PRESUPUESTO"."BVTCAT2" 
   (	"B_CODCAT1" VARCHAR2(10 BYTE), 
	"CODCAT2" VARCHAR2(10 BYTE), 
	"DESCAT2" VARCHAR2(50 BYTE), 
	"USRCRE" VARCHAR2(30 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(30 BYTE), 
	"FECACT" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
 

   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT2"."B_CODCAT1" IS 'Código de categoria 1';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT2"."CODCAT2" IS 'Código de categoría 2';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT2"."DESCAT2" IS 'Descripción  de categoría 2';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT2"."USRCRE" IS 'Usuario de creación de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT2"."FECCRE" IS 'Fecha de creación de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT2"."USRACT" IS 'Usuario de actualización de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT2"."FECACT" IS 'fecha de actualización de registro';
 
   COMMENT ON TABLE "PRESUPUESTO"."BVTCAT2"  IS 'Categoría2';
--------------------------------------------------------
--  DDL for Table BVTCAT3
--------------------------------------------------------

  CREATE TABLE "PRESUPUESTO"."BVTCAT3" 
   (	"B_CODCAT1" VARCHAR2(10 BYTE), 
	"B_CODCAT2" VARCHAR2(10 BYTE), 
	"CODCAT3" VARCHAR2(10 BYTE), 
	"DESCAT3" VARCHAR2(50 BYTE), 
	"USRCRE" VARCHAR2(30 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(30 BYTE), 
	"FECACT" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
 

   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT3"."B_CODCAT1" IS 'Código de categoria 1';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT3"."B_CODCAT2" IS 'Código de categoría2';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT3"."CODCAT3" IS 'Código de categoría 3';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT3"."DESCAT3" IS 'Descripción de categoría 3';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT3"."USRCRE" IS 'Usuario de creación de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT3"."FECCRE" IS 'Fecha de actualización de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT3"."USRACT" IS 'usuario de actualización de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT3"."FECACT" IS 'Fecha de actualización de registro';
 
   COMMENT ON TABLE "PRESUPUESTO"."BVTCAT3"  IS 'Categoria3';
--------------------------------------------------------
--  DDL for Table BVTCAT4
--------------------------------------------------------

  CREATE TABLE "PRESUPUESTO"."BVTCAT4" 
   (	"B_CODCAT1" VARCHAR2(10 BYTE), 
	"B_CODCAT2" VARCHAR2(10 BYTE), 
	"B_CODCAT3" VARCHAR2(10 BYTE), 
	"CODCAT4" VARCHAR2(10 BYTE), 
	"DESCAT4" VARCHAR2(50 BYTE), 
	"USRCRE" VARCHAR2(30 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(30 BYTE), 
	"FECACT" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
 

   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT4"."B_CODCAT1" IS 'Código de categoría1';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT4"."B_CODCAT2" IS 'Código de categoría2';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT4"."B_CODCAT3" IS 'Código de categoría3';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT4"."CODCAT4" IS 'Código de categoría4';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT4"."USRCRE" IS 'Usuario de creación de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT4"."FECCRE" IS 'Fecha de creación de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT4"."USRACT" IS 'Usuario de actualización de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTCAT4"."FECACT" IS 'Fecha de actualización de registro';
 
   COMMENT ON TABLE "PRESUPUESTO"."BVTCAT4"  IS 'Categoria4';
--------------------------------------------------------
--  DDL for Table BVTMENU
--------------------------------------------------------

  CREATE TABLE "PRESUPUESTO"."BVTMENU" 
   (	"B_CODROL" VARCHAR2(5 BYTE), 
	"CODOPC" VARCHAR2(4 BYTE), 
	"DESOPC" VARCHAR2(50 BYTE), 
	"CODVIS" VARCHAR2(1 BYTE), 
	"USRCRE" VARCHAR2(30 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(30 BYTE), 
	"FECACT" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
 

   COMMENT ON COLUMN "PRESUPUESTO"."BVTMENU"."B_CODROL" IS 'USUARIO ACCESO AL MENU';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTMENU"."CODOPC" IS 'NUMERO DE OPCION';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTMENU"."DESOPC" IS 'DESCRIPCION DE OPCION';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTMENU"."CODVIS" IS 'VISUALIZA 0, NO VISUALIZA 1';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTMENU"."USRCRE" IS 'USUARIO DE CREACION DE REGISTRO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTMENU"."FECCRE" IS 'FECHA DE CREACION DE REGISTRO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTMENU"."USRACT" IS 'USUARIO DE ACTUALIZACION DE REGISTRO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVTMENU"."FECACT" IS 'FECHA DE ACTUALIZACION DE REGISTRO';
 
   COMMENT ON TABLE "PRESUPUESTO"."BVTMENU"  IS 'MENU';
--------------------------------------------------------
--  DDL for Table BVT001
--------------------------------------------------------

  CREATE TABLE "PRESUPUESTO"."BVT001" 
   (	"CODREP" VARCHAR2(15 BYTE), 
	"DESREP" VARCHAR2(50 BYTE), 
	"COMREP" VARCHAR2(50 BYTE), 
	"USRCRE" VARCHAR2(30 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(30 BYTE), 
	"FECACT" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
 

   COMMENT ON COLUMN "PRESUPUESTO"."BVT001"."CODREP" IS 'CODIGO DE REPORTE';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT001"."DESREP" IS 'DESCRIPCION DEL REPORTE';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT001"."COMREP" IS 'COMENTARIO ADICIONAL';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT001"."USRCRE" IS 'USUARIO DE CREACION';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT001"."FECCRE" IS 'FECHA DE CREACION';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT001"."USRACT" IS 'USUARIO QUE ACTUALIZ¿ EL REGISTRO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT001"."FECACT" IS 'FECHA DE ACTUALIZACION DE REGISTRO';
 
   COMMENT ON TABLE "PRESUPUESTO"."BVT001"  IS 'REPORTES';
--------------------------------------------------------
--  DDL for Table BVT002
--------------------------------------------------------

  CREATE TABLE "PRESUPUESTO"."BVT002" 
   (	"CODUSER" VARCHAR2(10 BYTE), 
	"DESUSER" VARCHAR2(50 BYTE), 
	"CLUSER" VARCHAR2(10 BYTE), 
	"B_CODROL" VARCHAR2(5 BYTE), 
	"USRCRE" VARCHAR2(30 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(30 BYTE), 
	"FECACT" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
 

   COMMENT ON COLUMN "PRESUPUESTO"."BVT002"."CODUSER" IS 'CODIGO DE USUARIO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT002"."DESUSER" IS 'NOMBRE DE USUARIO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT002"."CLUSER" IS 'CLAVE DE USUARIO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT002"."B_CODROL" IS 'CODIGO DEL ROL';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT002"."USRCRE" IS 'USUARIO DE CREACION DE REGISTRO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT002"."FECCRE" IS 'FECHA DE CREACION DE REGISTRO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT002"."USRACT" IS 'USUARIO QUE ACTUALIZ¿ EL REGISTRO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT002"."FECACT" IS 'FECHA DE ACTUALIZACION DE REGISTRO';
 
   COMMENT ON TABLE "PRESUPUESTO"."BVT002"  IS 'USUARIOS';
--------------------------------------------------------
--  DDL for Table BVT003
--------------------------------------------------------

  CREATE TABLE "PRESUPUESTO"."BVT003" 
   (	"CODROL" VARCHAR2(5 BYTE), 
	"DESROL" VARCHAR2(50 BYTE), 
	"USRCRE" VARCHAR2(30 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(30 BYTE), 
	"FECACT" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
 

   COMMENT ON COLUMN "PRESUPUESTO"."BVT003"."CODROL" IS 'CODIGO DEL ROL';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT003"."DESROL" IS 'DESCRIPCION DEL ROL';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT003"."USRCRE" IS 'USUARIO DE CREACION DE REGISTRO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT003"."FECCRE" IS 'FECHA DE CREACION DE REGISTRO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT003"."USRACT" IS 'USUARIO QUE ACTUALIZ¿ EL REGISTRO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT003"."FECACT" IS 'FECHA DE ACTUALIZACION DE REGISTRO';
 
   COMMENT ON TABLE "PRESUPUESTO"."BVT003"  IS 'ROLES';
--------------------------------------------------------
--  DDL for Table BVT004
--------------------------------------------------------

  CREATE TABLE "PRESUPUESTO"."BVT004" 
   (	"B_CODROL" VARCHAR2(5 BYTE), 
	"B_CODREP" VARCHAR2(50 BYTE), 
	"B_DESREP" VARCHAR2(50 BYTE), 
	"B_COMREP" VARCHAR2(50 BYTE), 
	"USRCRE" VARCHAR2(30 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(30 BYTE), 
	"FECACT" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
 

   COMMENT ON COLUMN "PRESUPUESTO"."BVT004"."B_CODROL" IS 'CODIGO DEL ROL';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT004"."B_CODREP" IS 'CODIGO DEL REPORTE';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT004"."B_DESREP" IS 'DESCRIPCION DEL REPORTE';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT004"."B_COMREP" IS 'COMENTARIO DEL REPORTE';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT004"."USRCRE" IS 'USUARIO DE CREACION DE REGISTRO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT004"."FECCRE" IS 'FECHA DE CREACION DE REGISTRO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT004"."USRACT" IS 'USUARIO QUE DE ACTUALIZACION DE REGISTRO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT004"."FECACT" IS 'FECHA DE ACTUALIZACION DE REGISTRO';
 
   COMMENT ON TABLE "PRESUPUESTO"."BVT004"  IS 'OPCIONES ROLES';
--------------------------------------------------------
--  DDL for Table BVT005
--------------------------------------------------------

  CREATE TABLE "PRESUPUESTO"."BVT005" 
   (	"B_CODROL" VARCHAR2(5 BYTE), 
	"CODOPC" VARCHAR2(2 BYTE), 
	"DESOPC" VARCHAR2(50 BYTE), 
	"CODVIS" VARCHAR2(1 BYTE), 
	"USRCRE" VARCHAR2(30 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(30 BYTE), 
	"FECACT" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
 

   COMMENT ON COLUMN "PRESUPUESTO"."BVT005"."B_CODROL" IS 'ROL ACCESO A BOTONES';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT005"."CODOPC" IS 'NUMERO DE OPCION';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT005"."DESOPC" IS 'DESCRIPCION DE OPCION';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT005"."CODVIS" IS 'VISUALIZA 0, NO VISUALIZA 1';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT005"."USRCRE" IS 'USUARIO DE CREACION DE REGISTRO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT005"."FECCRE" IS 'FECHA DE CREACION DE REGISTRO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT005"."USRACT" IS 'USUARIO DE ACTUALIZACION DE REGISTRO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT005"."FECACT" IS 'FECHA DE ACTUALIZACION DE REGISTRO';
 
   COMMENT ON TABLE "PRESUPUESTO"."BVT005"  IS 'ACCESO A BOTONES';
--------------------------------------------------------
--  DDL for Table BVT006
--------------------------------------------------------

  CREATE TABLE "PRESUPUESTO"."BVT006" 
   (	"B_CODREP" VARCHAR2(15 BYTE), 
	"B_DESREP" VARCHAR2(50 BYTE), 
	"B_CODUSER" VARCHAR2(10 BYTE), 
	"FECACC" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
 

   COMMENT ON COLUMN "PRESUPUESTO"."BVT006"."B_CODREP" IS 'CODIGO DE REPORTE';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT006"."B_DESREP" IS 'DESCRCIPCION DE REPORTE';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT006"."B_CODUSER" IS 'USUARIO QUE ACCESO AL REPORTE';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT006"."FECACC" IS 'FECHA EN LA QUE ACCESO AL REPORTE';
 
   COMMENT ON TABLE "PRESUPUESTO"."BVT006"  IS 'AUDITORIA DE REPORTES';
--------------------------------------------------------
--  DDL for Table BVT007
--------------------------------------------------------

  CREATE TABLE "PRESUPUESTO"."BVT007" 
   (	"B_CODROL" VARCHAR2(5 BYTE), 
	"B_CODREP" VARCHAR2(15 BYTE), 
	"USRCRE" VARCHAR2(30 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(30 BYTE), 
	"FECACT" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
 

   COMMENT ON COLUMN "PRESUPUESTO"."BVT007"."B_CODROL" IS 'Código de rol';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT007"."B_CODREP" IS 'Código de reporte';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT007"."USRCRE" IS 'Usuario de creación de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT007"."FECCRE" IS 'Fecha de creación de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT007"."USRACT" IS 'Usuario de actualización de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."BVT007"."FECACT" IS 'Fecha de actualización de registro';
 
   COMMENT ON TABLE "PRESUPUESTO"."BVT007"  IS 'ACCESO  A REPORTES POR ROL (NEGAR)';
--------------------------------------------------------
--  DDL for Table GRUPCTO
--------------------------------------------------------

  CREATE TABLE "PRESUPUESTO"."GRUPCTO" 
   (	"CODGRUP" VARCHAR2(10 BYTE), 
	"DESGRUP" VARCHAR2(50 BYTE), 
	"USRCRE" VARCHAR2(30 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(30 BYTE), 
	"FECACT" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
 

   COMMENT ON COLUMN "PRESUPUESTO"."GRUPCTO"."USRCRE" IS 'USUARIO DE CREACION DE REGISTRO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."GRUPCTO"."FECCRE" IS 'FECHA DE CREACION DE REGISTRO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."GRUPCTO"."USRACT" IS 'USUARIO QUE ACTUALIZ¿ EL REGISTRO';
 
   COMMENT ON COLUMN "PRESUPUESTO"."GRUPCTO"."FECACT" IS 'FECHA DE ACTUALIZACION DE REGISTRO';
 
   COMMENT ON TABLE "PRESUPUESTO"."GRUPCTO"  IS 'ROLES';
--------------------------------------------------------
--  DDL for Table GRUPCTO_AGRUP
--------------------------------------------------------

  CREATE TABLE "PRESUPUESTO"."GRUPCTO_AGRUP" 
   (	"B_CODGRUP" VARCHAR2(10 BYTE), 
	"CODCTO" NUMBER(4,0), 
	"USRCRE" VARCHAR2(15 BYTE), 
	"FECCRE" DATE, 
	"USRACT" VARCHAR2(20 BYTE), 
	"FECACT" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
 

   COMMENT ON COLUMN "PRESUPUESTO"."GRUPCTO_AGRUP"."B_CODGRUP" IS 'Categoría 4';
 
   COMMENT ON COLUMN "PRESUPUESTO"."GRUPCTO_AGRUP"."CODCTO" IS 'Código del proceso';
 
   COMMENT ON COLUMN "PRESUPUESTO"."GRUPCTO_AGRUP"."USRCRE" IS 'Usuario de creación de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."GRUPCTO_AGRUP"."FECCRE" IS 'fecha de creación';
 
   COMMENT ON COLUMN "PRESUPUESTO"."GRUPCTO_AGRUP"."USRACT" IS 'Usuario de actualización de registro';
 
   COMMENT ON COLUMN "PRESUPUESTO"."GRUPCTO_AGRUP"."FECACT" IS 'Fecha de actualización de registro';
 
   COMMENT ON TABLE "PRESUPUESTO"."GRUPCTO_AGRUP"  IS 'ASOCIACION DE CATEGORIA 4 A PROCESOS';
--------------------------------------------------------
--  DDL for Table T_RGIP001
--------------------------------------------------------

  CREATE TABLE "PRESUPUESTO"."T_RGIP001" 
   (	"ANOPRO" NUMBER(4,0), 
	"MESPRO" NUMBER(2,0), 
	"ANOCON" NUMBER(4,0), 
	"MESCON" NUMBER(2,0), 
	"SEMCON" NUMBER(2,0), 
	"FECINI" DATE, 
	"FECFIN" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
 

   COMMENT ON COLUMN "PRESUPUESTO"."T_RGIP001"."ANOPRO" IS 'Año de proceso';
 
   COMMENT ON COLUMN "PRESUPUESTO"."T_RGIP001"."MESPRO" IS 'Mes proceso';
 
   COMMENT ON COLUMN "PRESUPUESTO"."T_RGIP001"."ANOCON" IS 'Año contable';
 
   COMMENT ON COLUMN "PRESUPUESTO"."T_RGIP001"."MESCON" IS 'Mes contable';
 
   COMMENT ON COLUMN "PRESUPUESTO"."T_RGIP001"."SEMCON" IS 'Semana contable';
 
   COMMENT ON COLUMN "PRESUPUESTO"."T_RGIP001"."FECINI" IS 'Fecha de inicio';
 
   COMMENT ON COLUMN "PRESUPUESTO"."T_RGIP001"."FECFIN" IS 'Fecha final';
 
   COMMENT ON TABLE "PRESUPUESTO"."T_RGIP001"  IS 'Calendario';

--------------------------------------------------------
--  DDL for Index ACCCAT1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRESUPUESTO"."ACCCAT1_PK" ON "PRESUPUESTO"."ACCCAT1" ("B_CODROL", "B_CODCAT1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  DDL for Index ACCCAT2_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRESUPUESTO"."ACCCAT2_PK" ON "PRESUPUESTO"."ACCCAT2" ("B_CODROL", "B_CODCAT1", "B_CODCAT2") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  DDL for Index ACCCAT3_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRESUPUESTO"."ACCCAT3_PK" ON "PRESUPUESTO"."ACCCAT3" ("B_CODROL", "B_CODCAT1", "B_CODCAT2", "B_CODCAT3") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  DDL for Index ACCCAT4_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRESUPUESTO"."ACCCAT4_PK" ON "PRESUPUESTO"."ACCCAT4" ("B_CODROL", "B_CODCAT1", "B_CODCAT2", "B_CODCAT3", "B_CODCAT4") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  DDL for Index ASOCAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRESUPUESTO"."ASOCAT_PK" ON "PRESUPUESTO"."ASOCAT" ("B_CODCAT4", "CODPROC", "UORG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  DDL for Index BI_HISTORIALINV_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRESUPUESTO"."BI_HISTORIALINV_PK" ON "PRESUPUESTO"."BI_HISTORIALINV" ("UORG", "CART", "CPRO", "FEOP", "STAT", "TURN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 12845056 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  DDL for Index BVTCAT1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRESUPUESTO"."BVTCAT1_PK" ON "PRESUPUESTO"."BVTCAT1" ("CODCAT1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  DDL for Index BVTCAT2_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRESUPUESTO"."BVTCAT2_PK" ON "PRESUPUESTO"."BVTCAT2" ("B_CODCAT1", "CODCAT2") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  DDL for Index BVTCAT3_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRESUPUESTO"."BVTCAT3_PK" ON "PRESUPUESTO"."BVTCAT3" ("B_CODCAT1", "B_CODCAT2", "CODCAT3") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  DDL for Index BVTCAT4_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRESUPUESTO"."BVTCAT4_PK" ON "PRESUPUESTO"."BVTCAT4" ("B_CODCAT1", "B_CODCAT2", "B_CODCAT3", "CODCAT4") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  DDL for Index BVTMENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRESUPUESTO"."BVTMENU_PK" ON "PRESUPUESTO"."BVTMENU" ("B_CODROL", "CODOPC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  DDL for Index BVT001_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRESUPUESTO"."BVT001_PK" ON "PRESUPUESTO"."BVT001" ("CODREP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  DDL for Index BVT002_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRESUPUESTO"."BVT002_PK" ON "PRESUPUESTO"."BVT002" ("CODUSER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  DDL for Index BVT003_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRESUPUESTO"."BVT003_PK" ON "PRESUPUESTO"."BVT003" ("CODROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  DDL for Index BVT004_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRESUPUESTO"."BVT004_PK" ON "PRESUPUESTO"."BVT004" ("B_CODROL", "B_CODREP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  DDL for Index BVT005_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRESUPUESTO"."BVT005_PK" ON "PRESUPUESTO"."BVT005" ("B_CODROL", "CODOPC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  DDL for Index BVT006_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRESUPUESTO"."BVT006_PK" ON "PRESUPUESTO"."BVT006" ("B_CODREP", "B_DESREP", "B_CODUSER", "FECACC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  DDL for Index BVT007_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRESUPUESTO"."BVT007_PK" ON "PRESUPUESTO"."BVT007" ("B_CODROL", "B_CODREP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  DDL for Index GRUPCTO_AGRUP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRESUPUESTO"."GRUPCTO_AGRUP_PK" ON "PRESUPUESTO"."GRUPCTO_AGRUP" ("B_CODGRUP", "CODCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  DDL for Index GRUPCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRESUPUESTO"."GRUPCTO_PK" ON "PRESUPUESTO"."GRUPCTO" ("CODGRUP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  DDL for Index T_RGIP001_IDX
--------------------------------------------------------

  CREATE INDEX "PRESUPUESTO"."T_RGIP001_IDX" ON "PRESUPUESTO"."T_RGIP001" ("FECINI", "FECFIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  DDL for Index T_RGIP001_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRESUPUESTO"."T_RGIP001_PK" ON "PRESUPUESTO"."T_RGIP001" ("ANOPRO", "MESPRO", "ANOCON", "MESCON", "SEMCON") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM" ;
--------------------------------------------------------
--  Constraints for Table ACCCAT1
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."ACCCAT1" ADD CONSTRAINT "ACCCAT1_PK" PRIMARY KEY ("B_CODROL", "B_CODCAT1")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM"  ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT1" MODIFY ("B_CODROL" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT1" MODIFY ("B_CODCAT1" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACCCAT2
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."ACCCAT2" ADD CONSTRAINT "ACCCAT2_PK" PRIMARY KEY ("B_CODROL", "B_CODCAT1", "B_CODCAT2")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM"  ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT2" MODIFY ("B_CODROL" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT2" MODIFY ("B_CODCAT1" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT2" MODIFY ("B_CODCAT2" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACCCAT3
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."ACCCAT3" ADD CONSTRAINT "ACCCAT3_PK" PRIMARY KEY ("B_CODROL", "B_CODCAT1", "B_CODCAT2", "B_CODCAT3")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM"  ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT3" MODIFY ("B_CODROL" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT3" MODIFY ("B_CODCAT1" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT3" MODIFY ("B_CODCAT2" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT3" MODIFY ("B_CODCAT3" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACCCAT4
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."ACCCAT4" ADD CONSTRAINT "ACCCAT4_PK" PRIMARY KEY ("B_CODROL", "B_CODCAT1", "B_CODCAT2", "B_CODCAT3", "B_CODCAT4")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM"  ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT4" MODIFY ("B_CODROL" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT4" MODIFY ("B_CODCAT1" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT4" MODIFY ("B_CODCAT2" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT4" MODIFY ("B_CODCAT3" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT4" MODIFY ("B_CODCAT4" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASOCAT
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."ASOCAT" ADD CONSTRAINT "ASOCAT_PK" PRIMARY KEY ("B_CODCAT4", "CODPROC", "UORG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM"  ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."ASOCAT" MODIFY ("B_CODCAT4" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."ASOCAT" MODIFY ("CODPROC" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."ASOCAT" MODIFY ("UORG" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."ASOCAT" MODIFY ("FECCAM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BIAUDIT
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BIAUDIT" MODIFY ("FECACC" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BIAUDIT" MODIFY ("DETFAZ" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BIAUDIT" MODIFY ("RESULT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BVTCAT1
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BVTCAT1" ADD CONSTRAINT "BVTCAT1_PK" PRIMARY KEY ("CODCAT1")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM"  ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."BVTCAT1" MODIFY ("CODCAT1" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVTCAT1" MODIFY ("DESCAT1" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BVTCAT2
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BVTCAT2" ADD CONSTRAINT "BVTCAT2_PK" PRIMARY KEY ("B_CODCAT1", "CODCAT2")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM"  ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."BVTCAT2" MODIFY ("B_CODCAT1" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVTCAT2" MODIFY ("CODCAT2" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVTCAT2" MODIFY ("DESCAT2" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BVTCAT3
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BVTCAT3" ADD CONSTRAINT "BVTCAT3_PK" PRIMARY KEY ("B_CODCAT1", "B_CODCAT2", "CODCAT3")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM"  ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."BVTCAT3" MODIFY ("B_CODCAT1" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVTCAT3" MODIFY ("B_CODCAT2" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVTCAT3" MODIFY ("CODCAT3" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVTCAT3" MODIFY ("DESCAT3" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BVTCAT4
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BVTCAT4" ADD CONSTRAINT "BVTCAT4_PK" PRIMARY KEY ("B_CODCAT1", "B_CODCAT2", "B_CODCAT3", "CODCAT4")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM"  ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."BVTCAT4" MODIFY ("B_CODCAT1" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVTCAT4" MODIFY ("B_CODCAT2" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVTCAT4" MODIFY ("B_CODCAT3" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVTCAT4" MODIFY ("CODCAT4" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVTCAT4" MODIFY ("DESCAT4" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BVTMENU
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BVTMENU" ADD CONSTRAINT "BVTMENU_PK" PRIMARY KEY ("B_CODROL", "CODOPC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM"  ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."BVTMENU" MODIFY ("B_CODROL" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVTMENU" MODIFY ("CODOPC" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVTMENU" MODIFY ("DESOPC" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVTMENU" MODIFY ("CODVIS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BVT001
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BVT001" ADD CONSTRAINT "BVT001_PK" PRIMARY KEY ("CODREP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM"  ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."BVT001" MODIFY ("CODREP" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVT001" MODIFY ("DESREP" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVT001" MODIFY ("COMREP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BVT002
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BVT002" ADD CONSTRAINT "BVT002_PK" PRIMARY KEY ("CODUSER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM"  ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."BVT002" MODIFY ("CODUSER" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVT002" MODIFY ("DESUSER" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVT002" MODIFY ("CLUSER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BVT003
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BVT003" ADD CONSTRAINT "BVT003_PK" PRIMARY KEY ("CODROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM"  ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."BVT003" MODIFY ("CODROL" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVT003" MODIFY ("DESROL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BVT004
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BVT004" ADD CONSTRAINT "BVT004_PK" PRIMARY KEY ("B_CODROL", "B_CODREP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM"  ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."BVT004" MODIFY ("B_CODROL" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVT004" MODIFY ("B_CODREP" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVT004" MODIFY ("B_DESREP" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVT004" MODIFY ("B_COMREP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BVT005
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BVT005" ADD CONSTRAINT "BVT005_PK" PRIMARY KEY ("B_CODROL", "CODOPC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM"  ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."BVT005" MODIFY ("B_CODROL" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVT005" MODIFY ("CODOPC" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVT005" MODIFY ("DESOPC" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVT005" MODIFY ("CODVIS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BVT006
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BVT006" ADD CONSTRAINT "BVT006_PK" PRIMARY KEY ("B_CODREP", "B_DESREP", "B_CODUSER", "FECACC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM"  ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."BVT006" MODIFY ("B_CODREP" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVT006" MODIFY ("B_DESREP" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVT006" MODIFY ("B_CODUSER" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVT006" MODIFY ("FECACC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BVT007
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BVT007" ADD CONSTRAINT "BVT007_PK" PRIMARY KEY ("B_CODROL", "B_CODREP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM"  ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."BVT007" MODIFY ("B_CODROL" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."BVT007" MODIFY ("B_CODREP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRUPCTO
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."GRUPCTO" ADD CONSTRAINT "GRUPCTO_PK" PRIMARY KEY ("CODGRUP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM"  ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."GRUPCTO" MODIFY ("CODGRUP" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."GRUPCTO" MODIFY ("DESGRUP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRUPCTO_AGRUP
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."GRUPCTO_AGRUP" ADD CONSTRAINT "GRUPCTO_AGRUP_PK" PRIMARY KEY ("B_CODGRUP", "CODCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM"  ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."GRUPCTO_AGRUP" MODIFY ("B_CODGRUP" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."GRUPCTO_AGRUP" MODIFY ("CODCTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_RGIP001
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."T_RGIP001" MODIFY ("ANOPRO" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."T_RGIP001" MODIFY ("MESPRO" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."T_RGIP001" MODIFY ("ANOCON" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."T_RGIP001" MODIFY ("MESCON" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."T_RGIP001" MODIFY ("SEMCON" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."T_RGIP001" MODIFY ("FECINI" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."T_RGIP001" MODIFY ("FECFIN" NOT NULL ENABLE);
 
  ALTER TABLE "PRESUPUESTO"."T_RGIP001" ADD CONSTRAINT "T_RGIP001_PK" PRIMARY KEY ("ANOPRO", "MESPRO", "ANOCON", "MESCON", "SEMCON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "BDPNOM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACCCAT1
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."ACCCAT1" ADD CONSTRAINT "ACCCAT1CODCAT1_FK" FOREIGN KEY ("B_CODCAT1")
	  REFERENCES "PRESUPUESTO"."BVTCAT1" ("CODCAT1") ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT1" ADD CONSTRAINT "ACCCAT1ROL_FK" FOREIGN KEY ("B_CODROL")
	  REFERENCES "PRESUPUESTO"."BVT003" ("CODROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACCCAT2
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."ACCCAT2" ADD CONSTRAINT "ACCCAT2CODCAT1_FK" FOREIGN KEY ("B_CODCAT1")
	  REFERENCES "PRESUPUESTO"."BVTCAT1" ("CODCAT1") ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT2" ADD CONSTRAINT "ACCCAT2CODCAT2_FK" FOREIGN KEY ("B_CODCAT1", "B_CODCAT2")
	  REFERENCES "PRESUPUESTO"."BVTCAT2" ("B_CODCAT1", "CODCAT2") ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT2" ADD CONSTRAINT "ACCCAT2ROL_FK" FOREIGN KEY ("B_CODROL")
	  REFERENCES "PRESUPUESTO"."BVT003" ("CODROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACCCAT3
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."ACCCAT3" ADD CONSTRAINT "ACCCAT3CODCAT1_FK" FOREIGN KEY ("B_CODCAT1")
	  REFERENCES "PRESUPUESTO"."BVTCAT1" ("CODCAT1") ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT3" ADD CONSTRAINT "ACCCAT3CODCAT2_FK" FOREIGN KEY ("B_CODCAT1", "B_CODCAT2")
	  REFERENCES "PRESUPUESTO"."BVTCAT2" ("B_CODCAT1", "CODCAT2") ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT3" ADD CONSTRAINT "ACCCAT3CODCAT3_FK" FOREIGN KEY ("B_CODCAT1", "B_CODCAT2", "B_CODCAT3")
	  REFERENCES "PRESUPUESTO"."BVTCAT3" ("B_CODCAT1", "B_CODCAT2", "CODCAT3") ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT3" ADD CONSTRAINT "ACCCAT3ROL_FK" FOREIGN KEY ("B_CODROL")
	  REFERENCES "PRESUPUESTO"."BVT003" ("CODROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACCCAT4
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."ACCCAT4" ADD CONSTRAINT "ACCCAT4CODCAT1_FK" FOREIGN KEY ("B_CODCAT1")
	  REFERENCES "PRESUPUESTO"."BVTCAT1" ("CODCAT1") ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT4" ADD CONSTRAINT "ACCCAT4CODCAT2_FK" FOREIGN KEY ("B_CODCAT1", "B_CODCAT2")
	  REFERENCES "PRESUPUESTO"."BVTCAT2" ("B_CODCAT1", "CODCAT2") ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT4" ADD CONSTRAINT "ACCCAT4CODCAT3_FK" FOREIGN KEY ("B_CODCAT1", "B_CODCAT2", "B_CODCAT3")
	  REFERENCES "PRESUPUESTO"."BVTCAT3" ("B_CODCAT1", "B_CODCAT2", "CODCAT3") ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT4" ADD CONSTRAINT "ACCCAT4CODCAT4_FK" FOREIGN KEY ("B_CODCAT1", "B_CODCAT2", "B_CODCAT3", "B_CODCAT4")
	  REFERENCES "PRESUPUESTO"."BVTCAT4" ("B_CODCAT1", "B_CODCAT2", "B_CODCAT3", "CODCAT4") ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."ACCCAT4" ADD CONSTRAINT "ACCCAT4ROL_FK" FOREIGN KEY ("B_CODROL")
	  REFERENCES "PRESUPUESTO"."BVT003" ("CODROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BVTCAT2
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BVTCAT2" ADD CONSTRAINT "BVTCAT2_CAT1_FK" FOREIGN KEY ("B_CODCAT1")
	  REFERENCES "PRESUPUESTO"."BVTCAT1" ("CODCAT1") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BVTCAT3
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BVTCAT3" ADD CONSTRAINT "BVTCAT3CAT1_FK" FOREIGN KEY ("B_CODCAT1")
	  REFERENCES "PRESUPUESTO"."BVTCAT1" ("CODCAT1") ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."BVTCAT3" ADD CONSTRAINT "BVTCAT3CAT2_FK" FOREIGN KEY ("B_CODCAT1", "B_CODCAT2")
	  REFERENCES "PRESUPUESTO"."BVTCAT2" ("B_CODCAT1", "CODCAT2") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BVTCAT4
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BVTCAT4" ADD CONSTRAINT "BVTCAT4CAT1_FK" FOREIGN KEY ("B_CODCAT1")
	  REFERENCES "PRESUPUESTO"."BVTCAT1" ("CODCAT1") ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."BVTCAT4" ADD CONSTRAINT "BVTCAT4CAT2_FK" FOREIGN KEY ("B_CODCAT1", "B_CODCAT2")
	  REFERENCES "PRESUPUESTO"."BVTCAT2" ("B_CODCAT1", "CODCAT2") ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."BVTCAT4" ADD CONSTRAINT "BVTCAT4CAT3_FK" FOREIGN KEY ("B_CODCAT1", "B_CODCAT2", "B_CODCAT3")
	  REFERENCES "PRESUPUESTO"."BVTCAT3" ("B_CODCAT1", "B_CODCAT2", "CODCAT3") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BVTMENU
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BVTMENU" ADD CONSTRAINT "BVTMENUROL_FK" FOREIGN KEY ("B_CODROL")
	  REFERENCES "PRESUPUESTO"."BVT003" ("CODROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BVT002
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BVT002" ADD CONSTRAINT "BVT002_FK" FOREIGN KEY ("B_CODROL")
	  REFERENCES "PRESUPUESTO"."BVT003" ("CODROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BVT004
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BVT004" ADD CONSTRAINT "BVT001_FK" FOREIGN KEY ("B_CODREP")
	  REFERENCES "PRESUPUESTO"."BVT001" ("CODREP") ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."BVT004" ADD CONSTRAINT "BVT004_FK" FOREIGN KEY ("B_CODROL")
	  REFERENCES "PRESUPUESTO"."BVT003" ("CODROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BVT005
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BVT005" ADD CONSTRAINT "BVT005ROL_FK" FOREIGN KEY ("B_CODROL")
	  REFERENCES "PRESUPUESTO"."BVT003" ("CODROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BVT006
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BVT006" ADD CONSTRAINT "BVT006REP_FK" FOREIGN KEY ("B_CODREP")
	  REFERENCES "PRESUPUESTO"."BVT001" ("CODREP") ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."BVT006" ADD CONSTRAINT "BVT006USR_FK" FOREIGN KEY ("B_CODUSER")
	  REFERENCES "PRESUPUESTO"."BVT002" ("CODUSER") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BVT007
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."BVT007" ADD CONSTRAINT "BVT007REP_FK" FOREIGN KEY ("B_CODREP")
	  REFERENCES "PRESUPUESTO"."BVT001" ("CODREP") ENABLE;
 
  ALTER TABLE "PRESUPUESTO"."BVT007" ADD CONSTRAINT "BVT007ROL_FK" FOREIGN KEY ("B_CODROL")
	  REFERENCES "PRESUPUESTO"."BVT003" ("CODROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRUPCTO_AGRUP
--------------------------------------------------------

  ALTER TABLE "PRESUPUESTO"."GRUPCTO_AGRUP" ADD CONSTRAINT "GRUPCTO_AGRUP_GRUPCTO_FK1" FOREIGN KEY ("B_CODGRUP")
	  REFERENCES "PRESUPUESTO"."GRUPCTO" ("CODGRUP") ENABLE;
